---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Stop services
  service:
    name: "{{ item.value.service_name }}"
    enabled: yes
    state: "stopped"
    daemon_reload: yes
  with_dict: "{{ filtered_panko_services }}"
  when:
    - "item.value.group in group_names"
    - item.value.service_enabled | bool
  register: _stop
  until: _stop is success
  retries: 5
  delay: 2
  listen:
    - "Restart panko services"
    - "venv changed"

# NOTE (noonedeadpunk): Remove this task after Xena release
- name: Remove obsoleted policy.json
  file:
    path: "/etc/panko/policy.json"
    state: absent
  listen:
    - "Restart panko services"
    - "venv changed"

- name: Start services
  service:
    name: "{{ item.value.service_name }}"
    enabled: yes
    state: "started"
    daemon_reload: yes
  with_dict: "{{ filtered_panko_services }}"
  when:
    - "item.value.group in group_names"
    - item.value.service_enabled | bool
  register: _start
  until: _start is success
  retries: 5
  delay: 2
  listen:
    - "Restart panko services"
    - "venv changed"

# NOTE(noonedeadpunk): This task is created due to migration from apache to uwsgi
# which was introduced during train release. It can be dropped afterwards.
- name: Restart web server
  service:
    name: "{{ panko_system_service_name }}"
    enabled: yes
    state: "restarted"
    daemon_reload: yes
  failed_when: false
