---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install the panko components
  hosts: panko_all
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - include: common-tasks/os-lxc-container-setup.yml
    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-panko"
            dest: "/var/log/panko"
    - include: common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ panko_galera_user }}"
        password: "{{ panko_container_db_password }}"
        login_host: "{{ panko_galera_address }}"
        db_name: "{{ panko_galera_database }}"
      when: inventory_hostname == groups['panko_all'][0]
    - include: common-tasks/package-cache-proxy.yml
  roles:
    - role: "os_panko"
    - role: "openstack_openrc"
      tags:
        - openrc
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: panko_log_rotate
      rsyslog_client_log_dir: "/var/log/panko"
      rsyslog_client_config_name: "99-panko-rsyslog-client.conf"
      tags:
        - rsyslog
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - panko
